version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./infra/volumes/dev/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: r2d2
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d r2d2'"]
      interval: 30s
      timeout: 10s
      retries: 3

  django:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    restart: on-failure:10
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && npm install && npm run build && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./infra/volumes/dev/logs/nginx:/var/log/nginx
      - ./infra/nginx/dev/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - django
    tty: true

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025, 1080:1080 ]